#!/bin/sh
DIRECTORY="$( cd "$( dirname "$0" )" && pwd )"
sudo ln -sfn $DIRECTORY/webserver.service /etc/systemd/system/webserver.service
sudo systemctl daemon-reload
sudo systemctl enable webserver.service
sudo systemctl restart webserver
sudo systemctl status webserver
